
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Deekyech
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     * @param loggedInClient
     */
    Client loggedInClient;
    ArrayList<Client> onlineClientsList;
    public MainWindow(Client loggedInClient) {
        initComponents();
        setTitle(loggedInClient.getClientName());
        setLocationRelativeTo(null);
        this.loggedInClient = loggedInClient;
        listOnlineClients.setSelectedIndex(0);
        MainWindowEventHandling eventHandling = new MainWindowEventHandling(this);
        listOnlineClients.addMouseListener(eventHandling);
        txtMessage.addActionListener(eventHandling);
        btnSend.addActionListener(eventHandling);
    }

    private MainWindow() {
        initComponents();
    }
    public void updateOnlineClientsList(ArrayList<Client> onlineClients) {
        onlineClientsList = onlineClients;
        DefaultListModel<String> dlm = new DefaultListModel<String>();
        for(Client c:onlineClients) {
            dlm.addElement(c.getClientName());
            //mainFrameWindow.cp.addChatClient(c);
        }
        listOnlineClients.setModel(dlm);
    }
    public void appendToChats(String text) {
        txtAreaChats.append(text + "\n");
        
    }
    /*
        prepareMessage():
        This method will be called from MainWindowEventHandling on actionEvent generated by the txtMessage and btnSend.
        It will prepare a message object and call the sendMessage method in loggedInClient.
    */
    public void prepareMessage() {
        System.out.println("Message is: " + txtMessage.getText());
        String recieverName = listOnlineClients.getSelectedValue();
        long recieverPhone;
        for(Client c:onlineClientsList) {
            if(c.getClientName().equals(recieverName)) {
                recieverPhone = c.getClientPhone();
                loggedInClient.sendMessage(new Message(loggedInClient, c, txtMessage.getText().getBytes(), ChatSystemConstants.MESSAGE_TYPE_TEXT), recieverPhone);
            }
        }
        txtMessage.setText("");
    }
    public void setRecieverClientLabel(String text) {
        lblRecieverClientName.setText(text);
    }
    public String getListSelectedValue() {
        return listOnlineClients.getSelectedValue();
    }
    public String getSelectedReciever() {
        return listOnlineClients.getSelectedValue();
    }
    public void clearChatArea() {
        txtAreaChats.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameContainer = new javax.swing.JPanel();
        mouseDragPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        ChatsWindow = new javax.swing.JPanel();
        chatsContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatPreviewContainer = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listOnlineClients = new javax.swing.JList<>();
        ChatAreaPanel = new javax.swing.JPanel();
        txtMessage = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        DpAndNameContainer = new javax.swing.JPanel();
        lblRecieverClientName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaChats = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setResizable(false);

        FrameContainer.setBackground(new java.awt.Color(9, 58, 62));
        FrameContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mouseDragPanel.setOpaque(false);
        mouseDragPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouseDragPanelMouseDragged(evt);
            }
        });
        mouseDragPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouseDragPanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout mouseDragPanelLayout = new javax.swing.GroupLayout(mouseDragPanel);
        mouseDragPanel.setLayout(mouseDragPanelLayout);
        mouseDragPanelLayout.setHorizontalGroup(
            mouseDragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        mouseDragPanelLayout.setVerticalGroup(
            mouseDragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        FrameContainer.add(mouseDragPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));

        MenuPanel.setBackground(new java.awt.Color(0, 23, 31));

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        FrameContainer.add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 780));

        ChatsWindow.setOpaque(false);

        chatsContainer.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(31, 54, 61)));
        chatsContainer.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(183, 252, 255));
        jLabel1.setText("Chats");

        jSeparator1.setBackground(new java.awt.Color(183, 252, 255));
        jSeparator1.setForeground(new java.awt.Color(183, 252, 255));

        jScrollPane1.setBackground(new java.awt.Color(9, 58, 62));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setOpaque(false);

        chatPreviewContainer.setBackground(new java.awt.Color(9, 58, 62));

        listOnlineClients.setBackground(new java.awt.Color(9, 58, 62));
        listOnlineClients.setForeground(new java.awt.Color(183, 252, 255));
        listOnlineClients.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listOnlineClients);

        javax.swing.GroupLayout chatPreviewContainerLayout = new javax.swing.GroupLayout(chatPreviewContainer);
        chatPreviewContainer.setLayout(chatPreviewContainerLayout);
        chatPreviewContainerLayout.setHorizontalGroup(
            chatPreviewContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatPreviewContainerLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        chatPreviewContainerLayout.setVerticalGroup(
            chatPreviewContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatPreviewContainerLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(chatPreviewContainer);

        javax.swing.GroupLayout chatsContainerLayout = new javax.swing.GroupLayout(chatsContainer);
        chatsContainer.setLayout(chatsContainerLayout);
        chatsContainerLayout.setHorizontalGroup(
            chatsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chatsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chatsContainerLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(chatsContainerLayout.createSequentialGroup()
                        .addGroup(chatsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator1))
                        .addContainerGap())))
        );
        chatsContainerLayout.setVerticalGroup(
            chatsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatsContainerLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        ChatAreaPanel.setOpaque(false);

        txtMessage.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        btnSend.setText("Send");

        DpAndNameContainer.setOpaque(false);

        lblRecieverClientName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblRecieverClientName.setForeground(new java.awt.Color(183, 252, 255));
        lblRecieverClientName.setText("RecieverClientName");
        DpAndNameContainer.add(lblRecieverClientName);

        txtAreaChats.setBackground(new java.awt.Color(9, 58, 62));
        txtAreaChats.setColumns(20);
        txtAreaChats.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtAreaChats.setForeground(new java.awt.Color(255, 0, 0));
        txtAreaChats.setRows(5);
        txtAreaChats.setFocusable(false);
        txtAreaChats.setMaximumSize(new java.awt.Dimension(574, 576));
        txtAreaChats.setMinimumSize(new java.awt.Dimension(574, 566));
        txtAreaChats.setPreferredSize(new java.awt.Dimension(574, 566));
        jScrollPane2.setViewportView(txtAreaChats);

        javax.swing.GroupLayout ChatAreaPanelLayout = new javax.swing.GroupLayout(ChatAreaPanel);
        ChatAreaPanel.setLayout(ChatAreaPanelLayout);
        ChatAreaPanelLayout.setHorizontalGroup(
            ChatAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChatAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChatAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(DpAndNameContainer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ChatAreaPanelLayout.createSequentialGroup()
                        .addComponent(txtMessage)
                        .addGap(18, 18, 18)
                        .addComponent(btnSend)))
                .addContainerGap())
        );
        ChatAreaPanelLayout.setVerticalGroup(
            ChatAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChatAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DpAndNameContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ChatAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend))
                .addGap(603, 603, 603))
        );

        javax.swing.GroupLayout ChatsWindowLayout = new javax.swing.GroupLayout(ChatsWindow);
        ChatsWindow.setLayout(ChatsWindowLayout);
        ChatsWindowLayout.setHorizontalGroup(
            ChatsWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChatsWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ChatAreaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ChatsWindowLayout.setVerticalGroup(
            ChatsWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChatsWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChatsWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ChatAreaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chatsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        FrameContainer.add(ChatsWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 980, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrameContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrameContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mouseDragPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDragPanelMousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_mouseDragPanelMousePressed

    
    private void mouseDragPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDragPanelMouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen()-mouseX, evt.getYOnScreen()-mouseY);
    }//GEN-LAST:event_mouseDragPanelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        javax.swing.SwingUtilities.invokeLater(new Runnable(){
            public void run() {
                new MainWindow();
            }
        });
        
        
    }
    int mouseX, mouseY;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChatAreaPanel;
    private javax.swing.JPanel ChatsWindow;
    private javax.swing.JPanel DpAndNameContainer;
    private javax.swing.JPanel FrameContainer;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JButton btnSend;
    private javax.swing.JPanel chatPreviewContainer;
    private javax.swing.JPanel chatsContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblRecieverClientName;
    private javax.swing.JList<String> listOnlineClients;
    private javax.swing.JPanel mouseDragPanel;
    private javax.swing.JTextArea txtAreaChats;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
